export enum ModelType {
  USER = 'USER',
  TRIP = 'TRIP',
  WAY_STOP = 'WAY_STOP',
  TRIP_METADATA = 'TRIP_METADATA',
  RECOMMENDATION = 'RECOMMENDATION',
  ARTICLE = 'ARTICLE',
  PRODUCT = 'PRODUCT',
}
